@startuml
participant Navigateur
participant Vue

Navigateur->Controleur: POST/entrer une  note

Controleur->Controleur:verifier parametres

Controleur->DAO: noteEvalDao.insert(note)

DAO->SGBD: INSERT INTO noteEval

SGBD-->DAO: ok ou échec

DAO-->Controleur: ok SQLException

Controleur->Vue:noteEval.jsp

Vue->Navigateur:noter Eval avec erreurs


@enduml
