@startuml
participant Navigateur
participant Vue
== Afficher le formulaire ==
Navigateur -> Controleur: POST /afficheNotes?idEvaluation=...
Controleur -> Controleur: vérifier que\nidEvaluation est entier
Controleur -> DAO: afficheNoteDao.insert(idEvaluation)
DAO -> SGBD: SELECT ...°
SGBD --> DAO: ok ou échec°
DAO --> Controleur: List<Note>°
Controleur -> Vue: afficheNote.jsp
Vue --> Navigateur: formulaire rempli

@enduml
