@startuml
participant Navigateur
participant Vue

Navigateur->Controleur: POST/afficher les notes d'une évaluations

Controleur->Controleur:verifier parametres

Controleur->DAO: afficheNoteEvalDao.insert(note)

DAO->SGBD: INSERT INTO afficheNoteEval

SGBD-->DAO: ok ou échec

DAO-->Controleur: ok SQLException

Controleur->Vue:afficheNoteEval.jsp

Vue->Navigateur:afficher note Eval avec erreurs


@enduml
