@startuml
participant Navigateur
participant Vue

== Afficher sondage == 

Navigateur -> Controleur: GET / afficherSondage?idCanal=...
Controleur -> Controleur: idCanal entier ?
Controleur -> DAO: SELECT...
DAO -> SGBD: 
SGBD --> DAO: 
DAO --> Controleur: 
Controleur -> Controleur:
Controleur -> Vue: 
Vue -> Navigateur: 
 
@enduml
