@startuml
participant Navigateur
participant Vue
== Afficher le formulaire ==
Navigateur -> Controleur: GET /saisirNotes?idEvaluation=...
Controleur -> Controleur: vérifier que\nidEvaluation est entier
Controleur -> DAO: EvaluationDao.\ngetNotesByIdEvaluation(idEvaluation)
DAO -> SGBD: SELECT ...
SGBD --> DAO: lignes
DAO --> Controleur: List<Note>
Controleur -> Vue: AfficheNote.jsp
Vue --> Navigateur: formulaire rempli

@enduml
