@startuml
participant Navigateur
participant Vue

Navigateur -> Controleur: POST /questionnaire?idQuestionnaire=...
Controleur -> Controleur: idquestionnaire entier ?
Controleur -> DAO: QuestionnaireDao.\ngetById(idQuestionnaire)
DAO -> SGBD: SELECT id_Questionnaire, id_canal from questionnaire...
SGBD --> DAO: ligne ou échec
DAO --> Controleur: Questionnaire ou SQLException
Controleur -> Vue: lanceQuestionnaire.jsp
Vue -> Navigateur: Questionnaire avec idCanal et idQuestionnaire

@enduml