@startuml

participant Navigateur
participant Vue

== Soumettre ses données de connexion ==
Navigateur -> Controleur: GET /sondages?idCanal=...
Controleur -> Controleur: idCanal entier ?
Controleur -> Dao: SondageDao.\getByIdCanal(idCanal)
Dao -> SGBD: SELECT ...\nFROM question\nWHERE ...
SGBD --> Dao: lignes
Dao --> Controleur: List<Sondage>, ou SQLException
Controleur --> Vue: sondages.jsp
Vue --> Navigateur: liste des sondages
@enduml
