@startuml

participant Navigateur
participant Vue
Navigateur -> Controleur: GET /participants
Controleur -> Controleur: récupère le idPersonne\nde l'utilisateur connecté
Controleur -> DAO: ParticipantsDao.\ngetByIdFormateur(idPersonne)
DAO -> SGBD: SELECT ...\nFROM Participants...
SGBD --> DAO: lignes
DAO --> Controleur: List<Participants> ou SQLException
Controleur -> Vue: ParticipantsFormateur.jsp
Vue -> Navigateur: liste@enduml
@enduml



