@startuml
participant Navigateur
participant Vue
Navigateur -> Controleur: GET /qestionnaires
Controleur -> Controleur: récupère le idPersonne\nde l'utilisateur connecté
Controleur -> DAO: QuestionnaireDao.\ngetByIdFormateur(idPersonne)
DAO -> SGBD: SELECT ...\nFROM questionnaire...
SGBD --> DAO: lignes
DAO --> Controleur: List<Questionnaire> ou SQLException
Controleur -> Vue: questionnairesFormateur.jsp
Vue -> Navigateur: liste
@enduml
