@startuml
participant Navigateur
participant JS
participant Vue

== Saisir note ==
JS -> Controleur: POST /saisirNotes\navec idEvaluation, idEtudiant, note, commentaires
Controleur -> Controleur: com = new Com(...)
Controleur -> Controleur: *note = new Note(...)*
Controleur -> DAO: EvaluationDao.update(com)
Controleur -> DAO: *EvaluationDao.update(note)*
DAO -> SGBD: UPDATE com_evaluation...
DAO -> SGBD: *UPDATE note_evaluation...*
SGBD --> DAO: ok ou exception
DAO --> Controleur: ok ou SQLException
Controleur --> JS: 204 si ok,\nou code erreur sinon
JS --> Navigateur: ok ou message erreur
@enduml
