@startuml
participant Navigateur
participant Vue

Navigateur -> Controleur: POST /signalerPresence\navec idCanal
Controleur -> Controleur: verifier id_canal est entier
Controleur -> DAO: pesence_séanceDao.select* From membre_canal
DAO -> SGBD: SELECT * from membre_canal ...
SGBD --> DAO: List<Presence> ou échec
DAO --> Controleur:  List<Presence> ou SQLException
Controleur -> Vue: presence.jsp
Vue -> Navigateur:feuille de présence.
@enduml
