@startuml
participant Navigateur
participant Vue

Navigateur -> Controleur: GET /signalerPresence?iidSeance=...
Controleur -> Vue : signalerPresence.jsp
Vue --> Navigateur : Bouton pour signaler presence
Navigateur -> Controleur: POST /signalerPresence\navec idSeance
Controleur -> Controleur: idSeance entier ?
Controleur -> Controleur: récupérer idUser dans session
Controleur -> DAO: SeanceDao.\nsetPresent(idSeance, idPersonne, true)

DAO -> SGBD: INSERT INRO presence_seance ...
SGBD --> DAO: ok ou échec
DAO --> Controleur:  ok ou SQLException
Controleur -> Controleur : met la séance en session
Controleur -> Navigateur: redirect(presences?idSeance=...)
@enduml
